/**
 * Department dashboard (v2 §2 stretch): a large department runs many lists in
 * parallel and cross-covers freely — this screen answers "where is every
 * case, and what needs a reviewer" without opening any of them. Pure
 * derivation over the case summaries; clinical words only (v2 §6.4).
 */
import { departmentBoard, STAGE_TITLES, STATUS_WORDS } from "../lib/workflow";
import { STAGE_KEYS, STAGE_STATUSES, type CaseSummary, type Provider } from "../lib/schema";

export function DepartmentBoard({
  cases,
  providers,
  onSelect,
}: {
  cases: CaseSummary[];
  providers: Provider[];
  onSelect: (caseId: string) => void;
}) {
  const board = departmentBoard(cases);
  const name = (id: string | null) =>
    (id && providers.find((p) => p.provider_id === id)?.name) ?? id;

  return (
    <div className="min-h-0 flex-1 overflow-y-auto p-6">
      <div className="mx-auto w-full max-w-4xl space-y-6">
        <div>
          <h2 className="text-base font-semibold">Department</h2>
          <p className="mt-0.5 text-sm text-ink-secondary">
            Every case on the board, and what each one is waiting for.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          {STAGE_KEYS.map((key) => {
            const bucket = board.stages[key];
            return (
              <section
                key={key}
                className="rounded border border-surface-overlay bg-surface-raised p-4"
              >
                <h3 className="flex items-baseline justify-between text-sm font-semibold">
                  {STAGE_TITLES[key]}
                  <span className="text-2xl font-bold text-brand">{bucket.total}</span>
                </h3>
                <ul className="mt-2 space-y-1 text-sm text-ink-secondary">
                  {STAGE_STATUSES.filter((s) => (bucket.byStatus[s] ?? 0) > 0).map((s) => (
                    <li key={s}>
                      {bucket.byStatus[s]} {STATUS_WORDS[s]}
                    </li>
                  ))}
                  {bucket.total === 0 && <li className="text-ink-subtle">no cases here</li>}
                </ul>
              </section>
            );
          })}
        </div>

        <section>
          <h3 className="text-sm font-semibold">Waiting for a reviewer</h3>
          {board.needsReview.length === 0 ? (
            <p className="mt-1.5 text-sm text-ink-subtle">
              Nothing is waiting for review right now.
            </p>
          ) : (
            <div className="mt-1.5 space-y-1.5">
              {board.needsReview.map((row) => (
                <button
                  key={row.caseId}
                  type="button"
                  onClick={() => onSelect(row.caseId)}
                  className="flex min-h-[44px] w-full items-center justify-between rounded border border-surface-overlay bg-surface-raised px-4 py-2 text-left text-sm hover:border-brand"
                >
                  <span className="font-medium">{row.label}</span>
                  <span className="text-ink-secondary">
                    {STAGE_TITLES[row.stage]} · generated by {name(row.by) ?? "unknown"}
                  </span>
                </button>
              ))}
            </div>
          )}
        </section>

        <p className="text-sm text-ink-secondary">
          {board.conflicts > 0 ? (
            <span className="text-status-conflicting">
              {board.conflicts} conflicting claim{board.conflicts === 1 ? "" : "s"} across live
              cases.
            </span>
          ) : (
            "No outstanding conflicts across live cases."
          )}{" "}
          {board.complete} complete · {board.demo} review-only demo
          {board.demo === 1 ? "" : "s"}.
        </p>
      </div>
    </div>
  );
}
